"""baseline: bookmarks table

Revision ID: b8ddfbfa5ce8
Revises:
Create Date: 2026-08-23 21:47:06.090514

Hand-filled, not autogenerated: at the time this revision was created,
bookmarks.db already had the bookmarks table (built by Phase 2's
`create_all`), so autogenerate correctly saw no diff and left upgrade()/
downgrade() empty - it was stamped onto that pre-existing database rather
than run. That's fine for the database that already existed, but it leaves
a gap for anyone running this chain against a genuinely empty one (a fresh
clone, a CI database): bookmarks would never actually get created. Filling
these in for real - matching the Bookmark model exactly as it stood before
Phase 3's owner_id column - makes the chain replayable from scratch.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ddfbfa5ce8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("bookmarks")
