"""add category and description to bookmarks

Revision ID: ef0f5b20492e
Revises: 20a5d3e9eefc
Create Date: 2026-09-02 10:30:14.038886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0f5b20492e'
down_revision: Union[str, None] = '20a5d3e9eefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('bookmarks', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'description')
    op.drop_column('bookmarks', 'category')
    # ### end Alembic commands ###
